implement projection change
james-rae/ramp4-pcar4 pull request #3
Opened 2022-02-02 19:28 UTC by sharvenp

2022-02-02 20:42 UTC, james-rae requested changes
> Reviewed 11 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3)* status: 11 of 20 files reviewed, 8 unresolved discussions (waiting on @james-rae and @sharvenp)

___
*[packages/ramp-core/schema.json, line 53 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw-8GI2Obl1F2-zxhg:-Muw-8GI2Obl1F2-zxhh:bh4h32c) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/schema.json#L53)):*
> ```JSON
>                     "description": "Specifies the map of the overviewmap fixture",
>                     "properties": {
>                         "tileSchemas": {
> ```

not really part of your initiative, but given our overview is bound to the basemap config, feels strange that we're re-defining the same thing here. I feel overview fixture should be grabbing this information from the main config store.
I guess if we wanted an overview that has a different schema, this would be appropriate. But I would bet the fixture code doesn't support that, it's banking on the two maps being in synch.  Overview with different projection sounds like `fancy-overview` fixture.
___
*[packages/ramp-core/public/ramp-starter.js, line 56 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw04mh3L07lofbCXk-:-Muw04mi5z8OyFA7Tm5t:b4o6ib4) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/public/ramp-starter.js#L56)):*
> ```JavaScript
>                 }
>             },
>             lodSets: [
> ```

is there a reason for swapping this with full values? the `.defaultXYZ` methods are there to save us having this pile in our files.
___
*[packages/ramp-core/src/fixtures/basemap/screen.vue, line 48 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw1KFE4vutN5A55VDY:-Muw1KFE4vutN5A55VDZ:b-w3fym7) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/27edcfffd18ce4b5edaa927c62d11ab75c0f061d/packages/ramp-core/src/fixtures/basemap/screen.vue#L48)):*
> ```Vue
>                         </svg>
>                         <span class="text-blue-600 pl-5" v-truncate>{{
>                             $t('basemap.refresh')
> ```

curious why this warning went away? I would have expected it to remain and the text changes to "map reset" instead of "map refresh"

Or does your views hack mean we no longer reload / refresh at all?
___
*[packages/ramp-core/src/fixtures/overviewmap/default-config.js, line 29 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw0tZq24BOBLk9SYSe:-Muw0tZq24BOBLk9SYSf:b-mea7i4) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/fixtures/overviewmap/default-config.js#L29)):*
> ```JavaScript
>         }
>     ],
>     lodSets: [
> ```

i know you didn't change this, but again i'm wondering why we're not using the `default` methods here
___
*[packages/ramp-core/src/geo/api/graphic/geometry/extent.ts, line 15 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw5MHo0rNu2hJNmn78:-Muw5MHo0rNu2hJNmn79:b3c01co) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/api/graphic/geometry/extent.ts#L15)):*
> ```XML
> import { EsriExtent } from '@/geo/esri';
> import GeoJson from 'geojson';
> import { RampExtentConfig, RampSpatialReference } from '../../geo-defs';
> ```

if we still need this, should move to the `@/geo/api` bracket above.
___
*[packages/ramp-core/src/geo/api/graphic/geometry/extent.ts, line 125 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw4uRs4pN0_V6SpZfS:-Muw4uRs4pN0_V6SpZfT:bch7f03) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/api/graphic/geometry/extent.ts#L125)):*
> ```XML
>         id: IdDef,
>         configExtent: RampExtentConfig,
>         configSr?: RampSpatialReference
> ```

rather than this, I'd almost prefer we have our config schema just define proper extents. Yes, we duplicate the SR for each extent in the set, but it means extent definitions are consistent across the config, can easily drop in an esri server extent object, and we don't need this "alt format" parameter anymore.
___
*[packages/ramp-core/src/geo/map/overview-map.ts, line 123 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw8cerAXqCUueN_4Zp:-Muw8cerAXqCUueN_4Zq:b3gqxq1) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/map/overview-map.ts#L123)):*
> ```XML
>         );
> 
>         // Rewove all ui components
> ```

type-o. `Rewove`
___
*[packages/ramp-core/src/geo/map/ramp-map.ts, line 772 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw4RsMAQst2mV1acQx:-Muw4RsMAQst2mV1acQy:br67gsb) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/map/ramp-map.ts#L772)):*
> ```XML
>                 id: 'i_am_error_extent_set',
>                 spatialReference: {
>                     wkid: -1
> ```

use `4326`. wont cause fatal errors somewhere else.


<!-- Sent from Reviewable.io -->

2022-02-03 16:32 UTC, james-rae requested changes
Agree about the name, I'd call it `refreshMap` or `reloadMapView`. 

---

Notice most of the code in `MapAPI.createMap()` is actually doing the view setup; the map setup is in common. And how we have the funny flags and hacking the config store to allow us to re-use that code. Here's what I'm thinking instead.

New function `createMapView(?basemapId)`.

- Could be private.
- Contains most/all of the view setup currently in createMap.
- If no basemap param, uses `config.initialBasemapId`
- I think everything else can be derived from your private vars / config store

`createMap` calls above function without param (or alternately, make param manditory and createMap pipes in the initialBasemapId).
`refreshMap` does the handler cleanup stuff then calls above function with new basemap from reprojection event.

---

At a high level the overview map seems way too complicated. I guess it's trying to adapt to all sorts of custom scenarios. I think it should get dumbed down. Some comments peppered in the code, we can talk if it's not clear.

---

Thought: `CommonMapAPI` was written very early on thinking we could re-use code between 2D and 3D maps. I now question the value of this. 3D is so different we almost need a different build of RAMP. I'm considering pushing the view-based properties into the class, and taking code thats the same in `MapAPI` and `OverviewMapAPI` and putting it into the common class. Something to think on, could clean up a lot of duplicate code.

---

> The `MAP_BASEMAPCHANGE` event is fired in two different places

Curious about the "first" fire that happens when map is created. Is this to trigger the caption refresh? Would it make more sense for the caption code to just also listen for one of the map_created events and refresh itself there?

> Reviewed 3 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-:-Mv-QIr07eCpb0Frqtmv:ba0nu8n)* status: 14 of 20 files reviewed, 13 unresolved discussions (waiting on @james-rae and @sharvenp)

___
*[packages/ramp-core/src/fixtures/overviewmap/overviewmap.vue, line 151 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Mv-4XNm0rErqGcBRdA9:-Mv-4XNm0rErqGcBRdAA:bnbliz9) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/fixtures/overviewmap/overviewmap.vue#L151)):*
> ```Vue
>          */
>         reprojectOverview() {
>             // TODO: is there a better way to do this?
> ```

a few thoughts. 
one, since the overview map really isn't user/config customizable (i.e. no extra layers, no ui state changes), we could just nuke and re-create it. 
two, tied in to my other comment, we can just grab whatever the map currently has. Might need to adjust the timing a bit. E.g. the "reproject" event unhooks any active handlers and sets up a one-time listener for a second event, that being the main map has finished re-creating itself. the second listener then re-creates stuff, knowing the map exists and can just grab properties. 
___
*[packages/ramp-core/src/geo/api/map/extent-set.ts, line 12 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Mv-8keM3zxBgvULklGd:-Mv-8keM3zxBgvULklGe:b30pbpd) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/api/map/extent-set.ts#L12)):*
> ```XML
>     constructor(
>         id: string,
>         sr: SpatialReference,
> ```

lets align with our geometry and "forgiving" constructor parameter types. use type `SrDef`
___
*[packages/ramp-core/src/geo/api/map/extent-set.ts, line 18 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Mv-8qhr7vQ2HI66Wafi:-Mv-8qhr7vQ2HI66Wafj:b7n2rpl) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/api/map/extent-set.ts#L18)):*
> ```XML
>     ) {
>         this._id = id;
>         this._sr = sr;
> ```

this would become this.sr = SpatialReference.parseSR(sr);
___
*[packages/ramp-core/src/geo/api/map/extent-set.ts, line 32 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Mv-82Ro4JvJvrpkACip:-Mv-82Ro4JvJvrpkACiq:beozn3u) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/api/map/extent-set.ts#L32)):*
> ```XML
>     }
> 
>     get spatialReference(): SpatialReference {
> ```

while it's not a geometry, our geometries expose `.sr` figure we should keep consistent. also, we can probably be lazy with this and `.id` and just make a basic property, i don't see the need for getters/setters/private_underscore
___
*[packages/ramp-core/src/geo/map/ramp-map.ts, line 298 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Mv-OPjP1RDR4MoET-mr:-Mv-OPjP1RDR4MoET-ms:b-1ba90u) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/map/ramp-map.ts#L298)):*
> ```XML
> 
>         // Clean up map view
>         this._viewPromise = new DefPromise();
> ```

Mild pointer concerns here. We have code that ran and waited on this promise. Doing this makes a brand new reference, so anything that ran at application start would have no idea there was a new promise. Might not be major impacts, but for example I imagine the panguard class gets broken. We might need things that depend on the view to also listen for a reprojection event and handle it. Timing could be tricky too, as I think event fires before this promise gets re-created.


<!-- Sent from Reviewable.io -->

2022-02-03 18:03 UTC, james-rae commented
___
*[packages/ramp-core/src/geo/api/map/extent-set.ts, line 12 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Mv-8keM3zxBgvULklGd:-Mv-k7ZX8ak1prKJwyuO:b-4bs5v5) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/api/map/extent-set.ts#L12)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

lets align with our geometry and "forgiving" constructor parameter types. use type `SrDef`
</blockquote></details>

heh alternate thought, we drop this alltogether and use the SR on the default extent. the getter for `.sr` could just do the reach in. I think this aligns with the config schema comment I made about extent sets


<!-- Sent from Reviewable.io -->

2022-02-04 20:56 UTC, sharvenp reviewed
Donethanks to all of these, the only thing is that the overview map still adapts its basemap as much as it can, and will just use the main map's basemap if it can't do any better.

> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-:-Mv5W0xA6GivtqW2yEU0:bd7xifj)* status: 4 of 23 files reviewed, 13 unresolved discussions (waiting on @james-rae)

___
*[packages/ramp-core/schema.json, line 53 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw-8GI2Obl1F2-zxhg:-Mv4wCVgBukxrKXu2q67:b5bz42h) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/schema.json#L53)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

not really part of your initiative, but given our overview is bound to the basemap config, feels strange that we're re-defining the same thing here. I feel overview fixture should be grabbing this information from the main config store.
I guess if we wanted an overview that has a different schema, this would be appropriate. But I would bet the fixture code doesn't support that, it's banking on the two maps being in synch.  Overview with different projection sounds like `fancy-overview` fixture.
</blockquote></details>

Donethanks, the main map config tile schema will now be used.
___
*[packages/ramp-core/public/ramp-starter.js, line 56 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw04mh3L07lofbCXk-:-Mv4wKYH95O6iHMAnut6:b-5o23fn) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/public/ramp-starter.js#L56)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

is there a reason for swapping this with full values? the `.defaultXYZ` methods are there to save us having this pile in our files.
</blockquote></details>

Donethanks, reverted these lists back to the default method calls.
___
*[packages/ramp-core/src/fixtures/basemap/screen.vue, line 48 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw1KFE4vutN5A55VDY:-Mv4wWZS3eNGHk3veZg3:b-sbtdd3) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/27edcfffd18ce4b5edaa927c62d11ab75c0f061d/packages/ramp-core/src/fixtures/basemap/screen.vue#L48)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

curious why this warning went away? I would have expected it to remain and the text changes to "map reset" instead of "map refresh"

Or does your views hack mean we no longer reload / refresh at all?
</blockquote></details>

Yup we are not doing a full reload or refresh, rather we are using this [R&D](https://github.com/ramp4-pcar4/ramp4-pcar4/issues/436) approach where we carefully recreate the map view while keeping the map untouched.
In other words, changing the basemap will feel the same regardless of the tile schema.
___
*[packages/ramp-core/src/fixtures/overviewmap/default-config.js, line 29 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw0tZq24BOBLk9SYSe:-Mv4xBVi18WLZyB_dC2Q:b-wi7oxp) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/fixtures/overviewmap/default-config.js#L29)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

i know you didn't change this, but again i'm wondering why we're not using the `default` methods here
</blockquote></details>

The overview map requires these specific lods so it looks a certain way (i.e. these are not the default values). Using the default lods makes it look more zoomed in.
___
*[packages/ramp-core/src/fixtures/overviewmap/overviewmap.vue, line 151 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Mv-4XNm0rErqGcBRdA9:-Mv4y0sa8Aotkr8yF8md:bev4v2c) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/fixtures/overviewmap/overviewmap.vue#L151)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

a few thoughts. 
one, since the overview map really isn't user/config customizable (i.e. no extra layers, no ui state changes), we could just nuke and re-create it. 
two, tied in to my other comment, we can just grab whatever the map currently has. Might need to adjust the timing a bit. E.g. the "reproject" event unhooks any active handlers and sets up a one-time listener for a second event, that being the main map has finished re-creating itself. the second listener then re-creates stuff, knowing the map exists and can just grab properties. 
</blockquote></details>

As discussed, I kept the "adapt basemap" behavior, but instead of following a chain of objects to fetch the tile schema id it now gets the id directly from the basemap store. 
If it can't find a suitable basemap, it will the main map's basemap while throwing a warning. We could even remove the warning and allow this behavior if they do not specify any basemaps in the overview map config. 
___
*[packages/ramp-core/src/geo/api/graphic/geometry/extent.ts, line 15 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw5MHo0rNu2hJNmn78:-Mv5EubN6OUMIhbNqXL0:bah2568) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/api/graphic/geometry/extent.ts#L15)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

if we still need this, should move to the `@/geo/api` bracket above.
</blockquote></details>

Donethanks
___
*[packages/ramp-core/src/geo/api/graphic/geometry/extent.ts, line 125 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw4uRs4pN0_V6SpZfS:-Mv57n9AAtlfCr-wdgk6:bah2568) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/api/graphic/geometry/extent.ts#L125)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

rather than this, I'd almost prefer we have our config schema just define proper extents. Yes, we duplicate the SR for each extent in the set, but it means extent definitions are consistent across the config, can easily drop in an esri server extent object, and we don't need this "alt format" parameter anymore.
</blockquote></details>

Donethanks
___
*[packages/ramp-core/src/geo/api/map/extent-set.ts, line 12 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Mv-8keM3zxBgvULklGd:-Mv5F9U-5YjE_Mn6Vkmr:bpdqxyp) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/api/map/extent-set.ts#L12)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

heh alternate thought, we drop this alltogether and use the SR on the default extent. the getter for `.sr` could just do the reach in. I think this aligns with the config schema comment I made about extent sets
</blockquote></details>

`.sr` now uses the default exent's SR. Though I decided to keep it as a public property without a getter/setter.
___
*[packages/ramp-core/src/geo/api/map/extent-set.ts, line 18 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Mv-8qhr7vQ2HI66Wafi:-Mv5FMJk9FYoiVbN-gFW:b-by5h89) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/geo/api/map/extent-set.ts#L18)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

this would become this.sr = SpatialReference.parseSR(sr);
</blockquote></details>

As mentioned above, `.sr` just clones the default extent's SR.
___
*[packages/ramp-core/src/geo/api/map/extent-set.ts, line 32 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Mv-82Ro4JvJvrpkACip:-Mv5FSOh8JhFZf1Vcy-p:bah2568) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b3 [...]

2022-02-07 14:34 UTC, sharvenp reviewed
One thing I forgot to mention is that I didn't move the basemap store update to `CommonMapAPI`'s `setBasemap` because this method is also used by the overview map to update its own basemap. Moving it here would cause the overview map's basemap to invade the basemap store, so I kept this store update call separate. 

> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-:-MvJaOaEAO5wa0lUIvkB:b-1q11qq)* status: 4 of 23 files reviewed, 13 unresolved discussions (waiting on @james-rae)



<!-- Sent from Reviewable.io -->

2022-02-07 20:37 UTC, james-rae requested changes
^ I see. Is there any trickery solutions? Like have `MapAPI` override with this code 
```
setBasemap(x) { 
  super.setBasemap(x);
  storeUpdater(x);
}
```

> Reviewed 13 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-:-MvKVfLH-JOhdHUfh5ny:bjg7pcb)* status: 17 of 23 files reviewed, 9 unresolved discussions (waiting on @james-rae and @sharvenp)

___
*[packages/ramp-core/schema.json, line 69 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvKWOKY414JF6zdoMT2:-MvKWOKY414JF6zdoMT3:bsm09rf) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/schema.json#L69)):*
> ```JSON
>                         "basemaps": {
>                             "type": "array",
>                             "description": "A list of basemaps to be made available for the overview map. Must provide one basemap for each tile schema provided in the main map config.",
> ```

Change from "Must" to "Can" or some other word to indicate it's optional.
___
*[packages/ramp-core/src/api/event.ts, line 189 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvKYTWc9Zth6DDqjMiK:-MvKYTWc9Zth6DDqjMiL:b4vvsyx) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/api/event.ts#L189)):*
> ```XML
> 
>     /**
>      * Fires when the map view ends reloading.
> ```

nitpick but can we say "refreshing" lol? Just to help avoid word salads later on. Same with event below.
___
*[packages/ramp-core/src/api/event.ts, line 790 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvK_rwWElDjI6cTC69s:-MvK_rwWElDjI6cTC69t:bue0ozb) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/api/event.ts#L790)):*
> ```XML
>             case DefEH.MAP_CREATED_ATTRIBUTION:
>                 zeHandler = () => {
>                     let mainMapConfig: RampMapConfig | undefined =
> ```

up to you, but you might be able to abstract the bulk of the two handlers into a local function that takes a target basemap id. In this handler, rather than use `mainMapConfig!.initialBasemapId`, you could use `$iApi.geo.map.getCurrentBasemapId()` which I think would exist at this point. Then you wouldn't need the store call both inside and outside the abstracted block.
___
*[packages/ramp-core/src/fixtures/basemap/item.vue, line 133 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvKbpx9Ct0bj5KHTzcW:-MvKbpx9Ct0bj5KHTzcX:b-94wmee) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/fixtures/basemap/item.vue#L133)):*
> ```Vue
>             );
> 
>             if (schemaChanged) {
> ```

further to my comment on the main PR thread, I feel almost all of this code should be in the primary map's `setBasemap` call. Assuming the trickery can work. Someone directly calling `setBasemap` without all this happening is pretty bad API / sadtimes party. Remember we can have a RAMP without a basemap selector (there are active RAMP2 sites that require this).

Alternately we put a TODO here noting the naughtyness and demanding a basemap refactor at a later time.
___
*[packages/ramp-core/src/fixtures/basemap/api/basemap.ts, line 44 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvKeYj0AUhGfwohqiB0:-MvKeYj0AUhGfwohqiB1:bbzw0pw) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/fixtures/basemap/api/basemap.ts#L44)):*
> ```XML
> 
>         if (basemap) {
>             this.$iApi.$vApp.$store.set(BasemapStore.selectedBasemap, basemap);
> ```

these would also be targeted to live inside the `MapAPI`, probably in the create map overload (again, assuming trickery, or put on the menu for a refactor)
___
*[packages/ramp-core/src/fixtures/basemap/store/basemap-store.ts, line 24 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvKesv25_I4X8obpCIP:-MvKesv25_I4X8obpCIQ:b-r3je9v) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/fixtures/basemap/store/basemap-store.ts#L24)):*
> ```XML
>      * (State) basemaps: Array<any>
>      */
>     basemaps = 'basemap/basemaps',
> ```

as part of all my grousing at trickery, it may be we want the actual basemap store as part of the core store, and have this fixture store only handle things that are relevant to the fixture state (selected / current stuff). But stores confuse me so maybe i'm wrong.
___
*[packages/ramp-core/src/fixtures/overviewmap/default-config.js, line 29 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw0tZq24BOBLk9SYSe:-MvKfPJj3zpkrR1j86lX:b-xqqdro) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/fixtures/overviewmap/default-config.js#L29)):*
<details><summary><i>Previously, sharvenp (Sharven Prasad Dhanasekar) wrote…</i></summary><blockquote>

The overview map requires these specific lods so it looks a certain way (i.e. these are not the default values). Using the default lods makes it look more zoomed in.
</blockquote></details>

Doesn't seem right to me. LODs should match the tiles, which scale level is visible at which time should be controlled by how we're changing the active view on the overview map.  Since this is a default, meaning a person can set their own values in fixture config (for custom basemap that only exists in overview, for example), would mean we'd have to have setup docs along the line of "you need to funny up your LODs to make this work, SIR, good luck!" which also indicates things are wrong on the inside.

I'd almost like to see the fixture steal the main maps LODs / extent sets as default; that way if someone is rocking a different tile set on their main viewer, they don't need to customize & duplicate the same thing on this fixture config to make stuff work. I'm not sure how feasible that is; depends on the timing I would imagine, the configuration of the main map needs to be available before this fixture starts up so it can consume it.

I'm already wrecking your world with changes, so my suggestion is nuke this hardcoded stuff, let the overview be "too zoomed in" and then open an issue to correct the extent-setting of the overview. It looks like it's currently trying to math it's way to a proper scale; we might want to instead create an extent that is a ratio of the "real extent" (e.g. 2x, 3x), then use map.setExtent instead of map.zoomMapTo . 


<!-- Sent from Reviewable.io -->

2022-02-08 14:18 UTC, james-rae requested changes
> Reviewed 2 of 19 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3)* status: 22 of 23 files reviewed, 12 unresolved discussions (waiting on @james-rae and @sharvenp)

___
*[packages/ramp-core/src/geo/map/common-map.ts, line 47 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvOeCgeEWmn23bDUg0V:-MvOeCgeEWmn23bDUg0W:b-erso25) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/geo/map/common-map.ts#L47)):*
> ```XML
>     //      a big bundle of properties like ESRI3 provided
> 
>     // NOTE while having this var be protected makes sense, there are also cases where other parts of the geoapi need to access this.
> ```

we can kill this note. I think we've settled on the `esriXYZ` and just accepting people can go wild
___
*[packages/ramp-core/src/geo/map/common-map.ts, line 56 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvOeu4c1LYud4HgZN0e:-MvOeu4c1LYud4HgZN0f:bgvzp1j) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/geo/map/common-map.ts#L56)):*
i think this comment was copied from the layer's view promise. Can be corrected and shortened

> a promise that resolves when the map view has been created
___
*[packages/ramp-core/src/geo/map/common-map.ts, line 144 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvOfgxt8XjCFkiWQ-Ug:-MvOfgxt8XjCFkiWQ-Uh:b-xdz6cw) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/geo/map/common-map.ts#L144)):*
> ```XML
> 
>     /**
>      * Reloads the map view by destroying it first and then recreating it
> ```

word police: "Refreshes the map view..."
___
*[packages/ramp-core/src/geo/map/common-map.ts, line 269 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvOg7Bl9jdA1ww-UVRq:-MvOg7Bl9jdA1ww-UVRr:bojdtwf) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/geo/map/common-map.ts#L269)):*
> ```XML
>         animate: boolean = true
>     ): Promise<void> {
>         // TODO technically this can accept any geometry. should we open up the suggested signatures to allow various things?
> ```

i think this todo is donethanks


<!-- Sent from Reviewable.io -->

2022-02-08 17:39 UTC, sharvenp reviewed
Yup that works, donethanks

> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-:-MvPK6Li5dERNZLTXFkN:b-g9qnk7)* status: 10 of 29 files reviewed, 12 unresolved discussions (waiting on @james-rae)

___
*[packages/ramp-core/schema.json, line 69 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvKWOKY414JF6zdoMT2:-MvPKAJb5rnNY5SaYgh0:bah2568) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/schema.json#L69)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Change from "Must" to "Can" or some other word to indicate it's optional.
</blockquote></details>

Donethanks
___
*[packages/ramp-core/src/api/event.ts, line 189 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvKYTWc9Zth6DDqjMiK:-MvPKBs3A8eA3tuZ2o7r:bah2568) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/api/event.ts#L189)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

nitpick but can we say "refreshing" lol? Just to help avoid word salads later on. Same with event below.
</blockquote></details>

Donethanks
___
*[packages/ramp-core/src/api/event.ts, line 790 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvK_rwWElDjI6cTC69s:-MvPKbpc9RqvWDUOhMWf:bt2qwz) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/api/event.ts#L790)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

up to you, but you might be able to abstract the bulk of the two handlers into a local function that takes a target basemap id. In this handler, rather than use `mainMapConfig!.initialBasemapId`, you could use `$iApi.geo.map.getCurrentBasemapId()` which I think would exist at this point. Then you wouldn't need the store call both inside and outside the abstracted block.
</blockquote></details>

The config store now has a property that keeps track of the currently active basemap. Hence now the `MAP_CREATED` and `MAP_BASEMAPCHANGE` handlers just make a direct call to the `updateAttribution` method with the basemap from the config store, but the `CONFIG_CHANGE` handler still reads the basemap from the config in the payload.
___
*[packages/ramp-core/src/fixtures/basemap/item.vue, line 133 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvKbpx9Ct0bj5KHTzcW:-MvPMtEb3n4Tb5vHQfzE:ba6spho) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/fixtures/basemap/item.vue#L133)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

further to my comment on the main PR thread, I feel almost all of this code should be in the primary map's `setBasemap` call. Assuming the trickery can work. Someone directly calling `setBasemap` without all this happening is pretty bad API / sadtimes party. Remember we can have a RAMP without a basemap selector (there are active RAMP2 sites that require this).

Alternately we put a TODO here noting the naughtyness and demanding a basemap refactor at a later time.
</blockquote></details>

Donethanks, the `selectBasemap` function has been simplified to just call `setBasemap` on the `MapAPI`.
Also, the `setBasemap` functionality where it updates the basemap on the `esriMap` has now been moved to a new protected method called `applyBasemap`. Now the new `setBasemap` will do basically what this `selectBasemap` function used to do. 
___
*[packages/ramp-core/src/fixtures/basemap/api/basemap.ts, line 44 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvKeYj0AUhGfwohqiB0:-MvPNBgB4xkvugGRnnMV:bo6030f) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/fixtures/basemap/api/basemap.ts#L44)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

these would also be targeted to live inside the `MapAPI`, probably in the create map overload (again, assuming trickery, or put on the menu for a refactor)
</blockquote></details>

The `BasemapAPI` has been nuked because the basemap store is gone. Since there is no store, there is no need to parse basemap config separately and the basemap fixture can pull the info directly from the main config store.
___
*[packages/ramp-core/src/fixtures/basemap/store/basemap-store.ts, line 24 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvKesv25_I4X8obpCIP:-MvPN_jB6HmMhdxlyeLm:bt94cfq) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/fixtures/basemap/store/basemap-store.ts#L24)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

as part of all my grousing at trickery, it may be we want the actual basemap store as part of the core store, and have this fixture store only handle things that are relevant to the fixture state (selected / current stuff). But stores confuse me so maybe i'm wrong.
</blockquote></details>

Donethanks, as mentioned above the basemap store now serves no purpose given that the basemaps and tile schemas lists can be pulled directly from the main config store, and also the config store keeps track of the currently selected basemap.
___
*[packages/ramp-core/src/fixtures/overviewmap/default-config.js, line 29 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-Muw0tZq24BOBLk9SYSe:-MvPP8tl1agy6b2X6i-D:b-hcnv0) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6a26e670ee14b28b32c7c26ecd3b4fca1ec4d9d8/packages/ramp-core/src/fixtures/overviewmap/default-config.js#L29)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Doesn't seem right to me. LODs should match the tiles, which scale level is visible at which time should be controlled by how we're changing the active view on the overview map.  Since this is a default, meaning a person can set their own values in fixture config (for custom basemap that only exists in overview, for example), would mean we'd have to have setup docs along the line of "you need to funny up your LODs to make this work, SIR, good luck!" which also indicates things are wrong on the inside.

I'd almost like to see the fixture steal the main maps LODs / extent sets as default; that way if someone is rocking a different tile set on their main viewer, they don't need to customize & duplicate the same thing on this fixture config to make stuff work. I'm not sure how feasible that is; depends on the timing I would imagine, the configuration of the main map needs to be available before this fixture starts up so it can consume it.

I'm already wrecking your world with changes, so my suggestion is nuke this hardcoded stuff, let the overview be "too zoomed in" and then open an issue to correct the extent-setting of the overview. It looks like it's currently trying to math it's way to a proper scale; we might want to instead create an extent that is a ratio of the "real extent" (e.g. 2x, 3x), then use map.setExtent instead of map.zoomMapTo . 
</blockquote></details>

Donethanks, will make a new issue to investigate this further.
___
*[packages/ramp-core/src/geo/map/common-map.ts, line 47 at r3](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvOeCgeEWmn23bDUg0V:-MvPMQ4F9tYcPvsgrMq4:bah2568) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/6f8feeb66ed283ab9a9906142f0d8d1f0b4262db/packages/ramp-core/src/geo/map/common-map.ts#L47)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

we can kill this note. I think we've settled on the `esriXYZ` and just accepting people can go wild
</blockquote></details>

Donethanks
___
*[packages/ramp-core/src/geo/map/common-map.ts, line 56 at r3](https://reviewable.io/rev [...]

2022-02-09 18:46 UTC, james-rae requested changes
PR is looking glorious now. Just a few remaining questions

> Reviewed 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-:-MvUnbix36-c21jiWwtg:b-psdjpm)* status: all files reviewed, 2 unresolved discussions (waiting on @sharvenp)

___
*[packages/ramp-core/src/fixtures/overviewmap/overviewmap.vue, line 143 at r5](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvUlIq2549KS5qP6gbI:-MvUlIq2549KS5qP6gbJ:b-ssk230) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/9cf285047af3700475d46436e9c4b85e1d3b81aa/packages/ramp-core/src/fixtures/overviewmap/overviewmap.vue#L143)):*
> ```Vue
>         },
> 
>         _adaptBasemap() {
> ```

lets add a comment to this function, explaining it handles when the main map changes projection. I went in circles a few times with a false assumption and thinking we had a new problem to solve lol.
___
*[packages/ramp-core/src/geo/map/common-map.ts, line 224 at r5](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvUmqL60s15ZZQ-hdoI:-MvUmqL60s15ZZQ-hdoJ:b-ttuj1p) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/9cf285047af3700475d46436e9c4b85e1d3b81aa/packages/ramp-core/src/geo/map/common-map.ts#L224)):*
> ```XML
>      * @returns {boolean} indicates if the schema has changed
>      */
>     setBasemap(basemapId: string): boolean {
> ```

one mild concern (and i could be mis-understanding, my reviewable-view has become a huge mess lol), this function is still technically part of `OverviewMapAPI` via inhertiance, but it loooks like the logic is more tailored to run only on the primary map??  Now our overview code is being smart enough not to call this, but if my hunch is correct, would it be worth overriding this in `OverviewMapAPI` and having it console error or some appropriate evasive action?  


<!-- Sent from Reviewable.io -->

2022-02-09 22:20 UTC, sharvenp reviewed
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3)* status: 25 of 29 files reviewed, 2 unresolved discussions (waiting on @james-rae)

___
*[packages/ramp-core/src/fixtures/overviewmap/overviewmap.vue, line 143 at r5](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvUlIq2549KS5qP6gbI:-MvVXn2DCUH-Kr5DXyDf:bah2568) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/9cf285047af3700475d46436e9c4b85e1d3b81aa/packages/ramp-core/src/fixtures/overviewmap/overviewmap.vue#L143)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

lets add a comment to this function, explaining it handles when the main map changes projection. I went in circles a few times with a false assumption and thinking we had a new problem to solve lol.
</blockquote></details>

Donethanks
___
*[packages/ramp-core/src/geo/map/common-map.ts, line 224 at r5](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvUmqL60s15ZZQ-hdoI:-MvVY6V2AuCADndUMlqT:bzdrw9a) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/9cf285047af3700475d46436e9c4b85e1d3b81aa/packages/ramp-core/src/geo/map/common-map.ts#L224)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

one mild concern (and i could be mis-understanding, my reviewable-view has become a huge mess lol), this function is still technically part of `OverviewMapAPI` via inhertiance, but it loooks like the logic is more tailored to run only on the primary map??  Now our overview code is being smart enough not to call this, but if my hunch is correct, would it be worth overriding this in `OverviewMapAPI` and having it console error or some appropriate evasive action?  
</blockquote></details>

Yea that's a valid point. `CommonMapAPI` shouldn't really be preferential to one map type, so I decided to make this "abstract". 
This implementation has been moved into `MapAPI` and the `OverviewMapAPI` will also override this where it will refresh itself with whatever basemap you give it and throw a warning if there a difference in tile schemas. 


<!-- Sent from Reviewable.io -->

2022-02-10 13:49 UTC, james-rae approved these changes
I bless this PR. 

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-:-MvYtLcyBbiGlE3mroJ2:b-xtjk4r)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sharvenp)

___
*[packages/ramp-core/src/fixtures/overviewmap/overviewmap.vue, line 201 at r6](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-MvYsyLt5r_oz8vxLI1B:-MvYsyLt5r_oz8vxLI1C:b99ik09) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/87b3cdc0f298564734c688fe53575a9e8c77132c/packages/ramp-core/src/fixtures/overviewmap/overviewmap.vue#L201)):*
> ```Vue
>                 // if we errored above, just use the main map's basemap
> 
>                 // TODO: do we want this warning? will throw on every map refresh if no basemaps have been provided in the config (which is valid)
> ```

leave as is for now (keep the TODO). I have a pending thing I want to tease out after this PR.


<!-- Sent from Reviewable.io -->

2022-02-10 14:03 UTC, sharvenp reviewed
Thanks for the review! I'll close this PR so it doesn't get spammed with any changes I push.

> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/3#-:-MvYvoNc0IPtluym68dZ:b2593nj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sharvenp)



<!-- Sent from Reviewable.io -->

2022-02-10 14:03 UTC, closed without merging