basic feature highlighting
james-rae/ramp4-pcar4 pull request #4
Opened 2022-04-04 14:49 UTC by elsa-huang

What it does so far:
- duplicate identified points onto the hilight layer
- apply the esri highlight onto those points
- clear the points
- identify on/off mode

[Demo](http://ramp4-app.azureedge.net/demo/users/elsa-huang/127-feature-hilight/host/index.html) 

I am bracing myself 😰

2022-04-05 14:17 UTC, james-rae requested changes
Had the map lock up after doing an identify (could not pan). It only happened once, so will treat as a glitch but keep an eye out for it. If you see it re-occurring then we might need to investigate wassup.

Half-done reviewing. Into meetings now, hope to look at the last big file before end of day.

> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-:-MztywImEjdnFzvxiAkr:b-1cfrgo)* status: 10 of 11 files reviewed, 8 unresolved discussions (waiting on @elsa-huang and @james-rae)

___
*[packages/ramp-core/src/api/event.ts, line 26 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-MztzEDi3vGQh9BzkDKe:-MztzEDi3vGQh9BzkDKf:b-xzvvvn) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/api/event.ts#L26)):*
> ```XML
> import { LayerStore } from '@/store/modules/layer';
> import { ConfigStore } from '@/store/modules/config';
> import { hilight } from '@/fixtures/hilight/store';
> ```

The naming here doesn't seem to match the ones above. Prob should be classname `HilightStore`
___
*[packages/ramp-core/src/api/event.ts, line 593 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mztzmzq-GGy5xWxUtJk:-Mztzmzq-GGy5xWxUtJl:boypsjo) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/api/event.ts#L593)):*
> ```XML
>                         hilightFix.clearHilightPoints();
>                         hilightFix.isIdentified = false;
>                     } else {
> ```

so this `else`, is this to implement the "first click does identify, second click clears highlight, third click does next identify"? If so, thats fine, maybe put a comment explaining wassup. Also might be worth logging a discussion to revisit this behavior. Maybe as a comment to the Identify Modes discussion.
___
*[packages/ramp-core/src/fixtures/hilight/hilight.vue, line 27 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mzu-np2DhJUhEnwOc_K:-Mzu-np2DhJUhEnwOc_L:bkrva3p) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/hilight.vue#L27)):*
> ```Vue
> 
>         // this.$iApi.event.on(GlobalEvents.MAP_CREATED, this.initLayer());
>         // MAP_EXTENTCHANGE seems like the wrong event but not MAP_CREATED doesn't work here
> ```

doesn't work as in it doesn't fire, or something else is broken? If it doesn't fire, it could be the map is already created? If that's the case, you can do something like

```
if (this.$iApi.geo.map.created) { initLayer }
else { event.on(MAP_CREATED, initLayer) }
```
___
*[packages/ramp-core/src/fixtures/hilight/hilight.vue, line 28 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mzu0Nqc7gH6q5ozu4sS:-Mzu0Nqc7gH6q5ozu4sT:boai9iq) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/hilight.vue#L28)):*
> ```Vue
>         // this.$iApi.event.on(GlobalEvents.MAP_CREATED, this.initLayer());
>         // MAP_EXTENTCHANGE seems like the wrong event but not MAP_CREATED doesn't work here
>         this.$iApi.event.on(
> ```

if we need to use this for now, I feel using `event.once()` is more appropriate than `event.on`, as you don't want this re-initializing every extent change? This code is probably adding a new highlight layer every pan lol.
___
*[packages/ramp-core/src/fixtures/hilight/hilight.vue, line 38 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mzu1GM72oJ48Dju-1Jx:-Mzu1GM72oJ48Dju-1Jy:b-ytpk3p) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/hilight.vue#L38)):*
> ```Vue
>         async initLayer() {
>             const hilightLayer = await this.$iApi.geo.layer.createLayer({
>                 id: 'Hilight',
> ```

lets name it something like `Ramp-Hilight` so someone snooping in the layer stack gets a clue its system generate. Hilight is an ugly word. `ight` don't look nice in a row. Who invented this language.
___
*[packages/ramp-core/src/fixtures/hilight/hilight.vue, line 48 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mzu1mhL2suzjOdDWaSm:-Mzu1mhL2suzjOdDWaSn:b-wy3v77) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/hilight.vue#L48)):*
> ```Vue
>         },
> 
>         populateHilight(identifyParams) {
> ```

if we're able to type the parameter it makes for happier devs
___
*[packages/ramp-core/src/geo/map/maptip.ts, line 81 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mzu2PnQAW-KatPqbwrw:-Mzu2PnQAW-KatPqbwrx:b-a9vl5r) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/geo/map/maptip.ts#L81)):*
> ```XML
>             return;
>         }
>         if (layerInstance.isCosmetic) {
> ```

put this into the if statement below, as an OR. I'm guessing the one below got added after you started development, so can blame git rebase for this one.
___
*[packages/ramp-core/src/geo/map/ramp-map.ts, line 130 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mzu2gdiD9CzVkQww267:-Mzu2gdiD9CzVkQww268:b90rgmw) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/geo/map/ramp-map.ts#L130)):*
> ```XML
>                     browserTouchPanEnabled: false
>                 },
>                 highlightOptions: {
> ```

add a TODO comment to make this configurable.


<!-- Sent from Reviewable.io -->

2022-04-05 15:59 UTC, james-rae requested changes
Operationally looks pretty good. A lot of raw ESRI code but as I said in a comment, we are a bit lacking for nice API's to handle styles/symbols at the moment. 

I think what comes next is to flush out what is on the main API, what type of use cases we want to handle, etc. That will guide what gets exposed. I get that what is here now is to support something that works and is testable.

> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-:-MzuRcNW82Kp4lNcskrn:b-b8395r)* status: 10 of 11 files reviewed, 13 unresolved discussions (waiting on @elsa-huang and @james-rae)

___
*[packages/ramp-core/src/fixtures/hilight/api/hilight.ts, line 29 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-MzuL_cF1SpG53YnCQNe:-MzuL_cF1SpG53YnCQNf:b-egi94k) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/api/hilight.ts#L29)):*
> ```XML
>      * @param identifyParams The identified results to highlight
>      */
>     populateHilightPoints(identifyParams: MapIdentifyResult) {
> ```

identified stuff can be things other than points, so maybe rename to `Geometries`, same with the clear function below.
___
*[packages/ramp-core/src/fixtures/hilight/api/hilight.ts, line 42 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-MzuNHHrEe8whjI6f3I-:-MzuNHHrEe8whjI6f3I0:bcne3oa) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/api/hilight.ts#L42)):*
> ```XML
>             const layer = this.$iApi.geo.layer.getLayer(l.result.uid);
>             // check for AttribLayer seems kind of scuffed rn but LayerInstance doesn't have renderer attr
>             if (layer instanceof AttribLayer && layer.renderer) {
> ```

you might be able to simply this with `layer.supportsAttributes`, though likely still need to cast to `AttribLayer` at some point to get the interface stuff.
___
*[packages/ramp-core/src/fixtures/hilight/api/hilight.ts, line 63 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-MzuPNXwBOb0mS6v-n5N:-MzuPNXwBOb0mS6v-n5O:bo8hxfj) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/api/hilight.ts#L63)):*
> ```XML
>                         } else {
>                             let geometry =
>                                 this.$iApi.geo.utils.geom.geomRampToEsri(
> ```

you can use shortcut `g.geometry.toESRI()`
___
*[packages/ramp-core/src/fixtures/hilight/api/hilight.ts, line 66 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-MzuQVQg-RG_gugut7ML:-MzuQVQg-RG_gugut7MM:bxyl62n) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/api/hilight.ts#L66)):*
> ```XML
>                                     g.geometry
>                                 );
> ```

lets add a TODO comment here. I understand why you're doing raw ESRI now. Once we get our `StyleOptions` api classes a bit stronger (i.e. better conversion between RAMP and ESRI, more support out of `SymbologyAPI`), we can simplify a lot of this code. Like just `getLayer` then calling `addGraphic()` on it, no need for esri classes.  So try to capture all that nonsense in a comment lol.
___
*[packages/ramp-core/src/fixtures/hilight/api/hilight.ts, line 75 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-MzuP-_SAhAkr3vS-CQ9:-MzuP-_SAhAkr3vS-CQA:b-99ztps) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/api/hilight.ts#L75)):*
> ```XML
>                             const hilightLayer =
>                                 this.$iApi.geo.layer.getLayer(
>                                     'Hilight'
> ```

since i'm seeing this twice now, maybe we can make the layer name a constant that gets exposed on HilightAPI or somewhere else that's useful?


<!-- Sent from Reviewable.io -->

2022-04-05 15:59 UTC, james-rae reviewed
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4)* status: all files reviewed, 13 unresolved discussions (waiting on @elsa-huang)



<!-- Sent from Reviewable.io -->

2022-04-08 11:55 UTC, james-rae requested changes
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4)* status: all files reviewed, 15 unresolved discussions (waiting on @elsa-huang)

___
*[packages/ramp-core/src/fixtures/hilight/api/hilight.ts, line 43 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N-8-hp82ch-lQWqsyth:-N-8-hp82ch-lQWqsyti:b-2tl1ge) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/api/hilight.ts#L43)):*
> ```XML
>             // check for AttribLayer seems kind of scuffed rn but LayerInstance doesn't have renderer attr
>             if (layer instanceof AttribLayer && layer.renderer) {
>                 l.result.loadPromise.then(async () => {
> ```

just sayin', after my current PR goes in the promise property will become `.loading`
___
*[packages/ramp-core/src/fixtures/hilight/api/hilight.ts, line 45 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N-80Ikg46xLD8WZck2_:-N-80Ikg46xLD8WZck2a:b-etf1h0) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/api/hilight.ts#L45)):*
> ```XML
>                 l.result.loadPromise.then(async () => {
>                     for (const item of l.result.items) {
>                         // get the Graphic's symbol
> ```

also, post current PR, the `items` will now have their own loading promise, so depending on what you're wanting to do, you need to handle that before attempting to get graphics and stuff. Since this code is sort-of like "test to make stuff appear", your best bet at the moment is probably wait for all nuggets to download, making it like the old way. So after waiting on the result promise above, you can then block on another promise consisting of `Promise.all(l.results.items.map(i => i.loading))`, then start your for loop after that promise chills.


<!-- Sent from Reviewable.io -->

2022-04-08 12:05 UTC, james-rae commented
*[packages/ramp-core/src/fixtures/hilight/api/hilight.ts, line 66 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-MzuQVQg-RG_gugut7ML:-N-834V95B9tSSVWHFrH:b2icd9w) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/api/hilight.ts#L66)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

lets add a TODO comment here. I understand why you're doing raw ESRI now. Once we get our `StyleOptions` api classes a bit stronger (i.e. better conversion between RAMP and ESRI, more support out of `SymbologyAPI`), we can simplify a lot of this code. Like just `getLayer` then calling `addGraphic()` on it, no need for esri classes.  So try to capture all that nonsense in a comment lol.
</blockquote></details>

I think https://github.com/ramp4-pcar4/ramp4-pcar4/issues/313 sort of captures this, though it's old issue and a bit out of date


<!-- Sent from Reviewable.io -->

2022-04-08 14:38 UTC, elsa-huang reviewed
Been working on stuff and not making any comments about it (classic Elsa)

> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-:-N-8an5G0U2G7C1JAV5p:b-n21mjs)* status: all files reviewed, 15 unresolved discussions (waiting on @elsa-huang and @james-rae)

___
*[packages/ramp-core/src/fixtures/hilight/hilight.vue, line 27 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mzu-np2DhJUhEnwOc_K:-N-8_Hxm04WosIszFW3O:b-wfky8u) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/hilight.vue#L27)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

doesn't work as in it doesn't fire, or something else is broken? If it doesn't fire, it could be the map is already created? If that's the case, you can do something like

```
if (this.$iApi.geo.map.created) { initLayer }
else { event.on(MAP_CREATED, initLayer) }
```
</blockquote></details>

I think it doesn't fire. I'll try this out
___
*[packages/ramp-core/src/fixtures/hilight/hilight.vue, line 38 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mzu1GM72oJ48Dju-1Jx:-N-8_NtYDi02HM2WlP-p:b6khbnk) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/hilight.vue#L38)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

lets name it something like `Ramp-Hilight` so someone snooping in the layer stack gets a clue its system generate. Hilight is an ugly word. `ight` don't look nice in a row. Who invented this language.
</blockquote></details>

highlight? :thinking: 
___
*[packages/ramp-core/src/fixtures/hilight/api/hilight.ts, line 45 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N-80Ikg46xLD8WZck2_:-N-8a6g3Cl3gavKqR-_k:b-ga8ydk) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/api/hilight.ts#L45)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

also, post current PR, the `items` will now have their own loading promise, so depending on what you're wanting to do, you need to handle that before attempting to get graphics and stuff. Since this code is sort-of like "test to make stuff appear", your best bet at the moment is probably wait for all nuggets to download, making it like the old way. So after waiting on the result promise above, you can then block on another promise consisting of `Promise.all(l.results.items.map(i => i.loading))`, then start your for loop after that promise chills.
</blockquote></details>

I remember us talking about this change during a RASC or something I think... I'll play around with it once the PR gets merged but its gonna be a bigger promises party I guess :tada: 


<!-- Sent from Reviewable.io -->

2022-04-08 18:08 UTC, james-rae commented
*[packages/ramp-core/src/fixtures/hilight/hilight.vue, line 38 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mzu1GM72oJ48Dju-1Jx:-N-9MB2nEwZp_ca283x-:b-9ebs7l) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/hilight.vue#L38)):*
<details><summary><i>Previously, elsa-huang wrote…</i></summary><blockquote>

highlight? :thinking: 
</blockquote></details>

lol.  nah leave as is. i'm just grousing. I tried `hilite` in ramp2 and people called me out on it


<!-- Sent from Reviewable.io -->

2022-04-14 17:38 UTC, james-rae commented
*[packages/ramp-core/src/api/event.ts, line 593 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mztzmzq-GGy5xWxUtJk:-N-d8rRZCBTB5bXNcyYZ:b-uloq2s) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/api/event.ts#L593)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

so this `else`, is this to implement the "first click does identify, second click clears highlight, third click does next identify"? If so, thats fine, maybe put a comment explaining wassup. Also might be worth logging a discussion to revisit this behavior. Maybe as a comment to the Identify Modes discussion.
</blockquote></details>

Fun notes: we need something to clear a highlight, so might be stuck with this. Need to ponder more.


<!-- Sent from Reviewable.io -->

2022-04-14 18:02 UTC, elsa-huang reviewed
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4)* status: all files reviewed, 15 unresolved discussions (waiting on @elsa-huang and @james-rae)

___
*[packages/ramp-core/src/api/event.ts, line 593 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mztzmzq-GGy5xWxUtJk:-N-OXwRQ0roChjs3PyhA:btjevze) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/api/event.ts#L593)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Fun notes: we need something to clear a highlight, so might be stuck with this. Need to ponder more.
</blockquote></details>

Had some thoughts about having a dedicated button somewhere to clear, but I also definitely need to ponder more on this one
___
*[packages/ramp-core/src/fixtures/hilight/hilight.vue, line 27 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-Mzu-np2DhJUhEnwOc_K:-N-O9YvQ-dlrLMzkOyxU:b7bebez) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/bcfacf3acecf2b733b1a9678c213464588531d5a/packages/ramp-core/src/fixtures/hilight/hilight.vue#L27)):*
<details><summary><i>Previously, elsa-huang wrote…</i></summary><blockquote>

I think it doesn't fire. I'll try this out
</blockquote></details>

Wrote this comment down at some point but never published it I guess

Actually, it looks like it fires, but then when trying to do the identify, I get a `"Could not find layer associated with 'Ramp-Hilight'"`. Using the below `event.once()` on `MAP_EXTENTCHANGE` for now

But yeah, will probably link my branch on Tuesday


<!-- Sent from Reviewable.io -->

2022-05-13 14:03 UTC, elsa-huang reviewed
Reviewable looks ok for the most part. Some of the TODOs and comments are just notes for myself, especially the chunky one at the bottom of `hilight.ts`. So if it seems like I'm just talking to myself there it's because I am lol.

I think this is everything that has been changed/added:
- Added `hilight-mode` classes
- (For GLOW hilighter) When the details panel is open on the items screen, it will highlight that one item. When the details panel is open on the layer screen, it will highlight all the results from that layer. It won't highlight all identified items from all layers at any point.
- The functionality to populate the hilight layer graphics using a Graphic was moved out of `populateFromIdentify()`. There's 2 different functions for that now, `populateHilightGraphicsFromSet()` and `populateHilightGraphics()`.  There's some notes on it in that chunky TODO, but we can also just talk about it in bilat if needed
- Graphics have a unique id now
- Have `HilightGraphic` and `HilightGraphicSet` types now

> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-:-N1xgH4E2KNQ7YEHoEdw:bxirp)* status: 0 of 26 files reviewed, 15 unresolved discussions (waiting on @elsa-huang and @james-rae)



<!-- Sent from Reviewable.io -->

2022-05-13 15:57 UTC, james-rae requested changes
> Reviewed 12 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4)* status: 12 of 26 files reviewed, 18 unresolved discussions (waiting on @elsa-huang and @james-rae)

___
*[`src/fixtures/details/item-screen.vue` line 177 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1y07hHE-BJHFSXtMpk:-N1y07hHE-BJHFSXtMpl:b-btyduk) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/details/item-screen.vue#L177)):*
> ```Vue
>         identifyItem(): IdentifyItem {
>             console.log(this.result.items[this.currentIdx]);
>             // highlight the identified item
> ```

would this block of code be better off in the `itemChanged()` method? Call it `.loaded` block of that? This is a computed method, which I think means it will execute whenever someone just wants to read what the current item is. `itemChanged` will run only when the item changes, and also gets called for the first item shown.
___
*[`src/fixtures/details/item-screen.vue` line 332 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1y0uHKEAJ52hWYNlHH:-N1y0uHKEAJ52hWYNlHI:b-tzldd3) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/details/item-screen.vue#L332)):*
> ```Vue
>          */
>         seeList() {
>             // hilight all geometries for this layer
> ```

this block is almost the same as the block above. I think you could abstract most of it to a common function. The code that sits in each does the layer check and just collates an array of `oid` and `uid` pairs, then passes to the common function. That bad boy can do the l fixture check, toggle party, and construct the gids.
___
*[`src/fixtures/gazebo/p2-screen-3.vue` line 57 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1y1T4u2ts0MGQrTtpI:-N1y1T4u2ts0MGQrTtpJ:b5nuejr) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/gazebo/p2-screen-3.vue#L57)):*
> ```Vue
> 
> <script lang="ts">
> import { defineComponent, type PropType } from 'vue';
> ```

oh buddy i think you found the source of those annoying console errors. :trophy: 
___
*[`src/fixtures/hilight/hilight.vue` line 2 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1y5asy9C3jYeJjVBPW:-N1y5asy9C3jYeJjVBPX:boq3zvv) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/hilight.vue#L2)):*
> ```Vue
> <template>
>     <div></div>
> ```

nice.
part of this makes me wonder if we need Vue at all. I think most of the code can just sit in `index.ts` and `hilight.ts`.  Maybe Vue makes it easier to work with the store...but the store is just holding one mighty boolean, and there is no two way binding, so that could just be state in the api maybe. In fact it might be doubled by `isIdentified` in the api.

Not demanding a change. But all a fixture needs is to have an id, and if it wants, functions like `added` and `removed`.


<!-- Sent from Reviewable.io -->

2022-05-16 20:54 UTC, james-rae requested changes
> Reviewed 11 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4)* status: 23 of 26 files reviewed, 10 unresolved discussions (waiting on @elsa-huang and @james-rae)

___
*[`src/fixtures/hilight/api/hilight.ts` line 40 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1yOB105VRQKJJgZuHC:-N1yOB105VRQKJJgZuHD:bi9l0kv) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/api/hilight.ts#L40)):*
> ```XML
>         }
> 
>         if (this.$iApi.geo.map.esriView) {
> ```

not 100% (still trying to assemble how everything hangs together), but you might want to wait on `map.viewPromise`. If there is no view (which maybe could happen if this goes early), then this logic would skip and never revist.  However the risk is you get a stack of `_parseConfig` requests and then they race when the view finally appears.  Maybe put a `TODO` for now to revist? Its the sort of thing to tidy up when all the guts are working.

Also we probably need a listener / watcher of sorts to detect when the esriView gets destroyed and recreated. The code below will need to be re-applied. Sharven has samples of this around his reprojection code. Look at mappy stuff like scrollguard and crosshairs if you cant find it.
___
*[`src/fixtures/hilight/api/hilight.ts` line 52 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1yP7jT6U0keHgvdKLY:-N1yP7jT6U0keHgvdKLZ:bwkqr3r) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/api/hilight.ts#L52)):*
> ```XML
> 
>     get config() {
>         return super.config;
> ```

redundant?
___
*[`src/fixtures/hilight/api/hilight.ts` line 67 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1yPWgs6vTKsnEMVI8K:-N1yPWgs6vTKsnEMVI8L:beae4bp) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/api/hilight.ts#L67)):*
> ```XML
>         if (hilightLayer && hilightLayer instanceof CommonGraphicLayer) {
>             const gs = graphics instanceof Array ? graphics : [graphics];
>             for (const graphic of gs) {
> ```

doesn't really matter, but if you want to avoid raw for loops you can do
```
await Promise.all(gs.map(g => hilightLayer.addGraphic(g)));
```

UNLESS they need to go one at a time, in order. in which case there might be a clever trick but I'm not seeing it so keep as is. `addGraphic` is only async due to it reprojecting any geometry into the map's spatial reference. For highlighting it should always be the same; and even if not, I don't see any concurrency collisions other than which duplicate-named graphic would error first.
___
*[`src/fixtures/hilight/api/hilight-defs.ts` line 2 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N2DNArH-kfmD2EQvc7d:-N2DNArH-kfmD2EQvc7e:b-uitus4) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/api/hilight-defs.ts#L2)):*
> ```XML
> import type { DefPromise, Graphic, IdentifyResult } from '@/geo/api';
> ```

You could put the layer name (`Ramp-Highlight`) in this file as a const then use it in the other spots.
___
*[`src/fixtures/hilight/api/hilight-mode/base-hilight-mode.ts` line 19 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N2DPRyC1dPWVx6QeAW1:-N2DPRyC1dPWVx6QeAW2:brqz3zt) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/api/hilight-mode/base-hilight-mode.ts#L19)):*
> ```XML
>     // Or can we configure toggleOn/toggleOff in the API to handle this? flag for it?
> 
>     // what about having more than 1 hilighter active? 🤔
> ```

nah. Let someone build a combo class that manages the merge inside it.  Having multiple random hiliters active could get all kinds of collisions; sharing layer fights, split layers in wrong order, effects in wrong order, etc.
___
*[`src/fixtures/hilight/api/hilight-mode/glow-hilight-mode.ts` line 30 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N2DOa-_6lGgco0SWhOO:-N2DOa-_6lGgco0SWhOP:b-in96il) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/api/hilight-mode/glow-hilight-mode.ts#L30)):*
> ```XML
>                 ?.then(function (layerView) {
>                     hGraphics.forEach((g: HilightGraphic) => {
>                         const graphic = hilightLayer.getEsriGraphic(
> ```

I'm assuming we need the actual ESRI graphic lurking in the layer, yeah? Makes sense I suppose. That's a shame, was hoping we could just fire of `.toESRI()` calls everywhere but that return value comes out of nowhere. The alternative is to have RAMP Graphics start tracking their ESRI counterparts with internal pointer, but then we're hardlinking to layers and RAMP Graphics are supposed to be :sparkles: ethereal :sparkles:
___
*[`src/geo/layer/common-graphic-layer.ts` line 149 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N2D8LfB3bW7dHyx30sk:-N2D8LfB3bW7dHyx30sl:b-akhbl1) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/geo/layer/common-graphic-layer.ts#L149)):*
> ```XML
>             // TODO remove hover stuff once supported
>             this.esriLayer.removeAll();
>             this._graphics.splice(0, this._graphics.length);
> ```

wow bad code on my part for not doing this.
___
*[`src/geo/map/maptip.ts` line 82 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1yTFXD2E7XQ9-yEHu1:-N1yTFXD2E7XQ9-yEHu2:bbjob22) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/geo/map/maptip.ts#L82)):*
> ```XML
>         }
> 
>         if (!layerInstance.hovertips || layerInstance.isCosmetic) {
> ```

lets add a TODO to remind us to remove this when we support hovers on RAMP graphics.  Theres similar code in CommonGraphicLayer (it always turns off hovertips; probably was done after you added this check)


<!-- Sent from Reviewable.io -->

2022-05-20 20:43 UTC, elsa-huang reviewed
Just marking stuff as acknowledged/resolved and putting notes on your comments! Happy long weekend :tada: 

> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-:-N2YBnDF3nJ_Fbc-MBu2:b4xaytc)* status: 23 of 26 files reviewed, 10 unresolved discussions (waiting on @james-rae)

___
*[`src/fixtures/details/item-screen.vue` line 177 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1y07hHE-BJHFSXtMpk:-N2Y8WPkDg8Z_h3MZGNi:b-1r4wyb) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/details/item-screen.vue#L177)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

would this block of code be better off in the `itemChanged()` method? Call it `.loaded` block of that? This is a computed method, which I think means it will execute whenever someone just wants to read what the current item is. `itemChanged` will run only when the item changes, and also gets called for the first item shown.
</blockquote></details>

yup, moved. donethanks
___
*[`src/fixtures/details/item-screen.vue` line 332 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1y0uHKEAJ52hWYNlHH:-N2Y8tFG9YvyGe4pvnvx:b-tnjobh) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/details/item-screen.vue#L332)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

this block is almost the same as the block above. I think you could abstract most of it to a common function. The code that sits in each does the layer check and just collates an array of `oid` and `uid` pairs, then passes to the common function. That bad boy can do the l fixture check, toggle party, and construct the gids.
</blockquote></details>

true :eye: :lips: :eye: donethanks!
___
*[`src/fixtures/hilight/hilight.vue` line 2 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1y5asy9C3jYeJjVBPW:-N2Y9IBi9KLb8qcGdhwC:bc3lc9j) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/hilight.vue#L2)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

nice.
part of this makes me wonder if we need Vue at all. I think most of the code can just sit in `index.ts` and `hilight.ts`.  Maybe Vue makes it easier to work with the store...but the store is just holding one mighty boolean, and there is no two way binding, so that could just be state in the api maybe. In fact it might be doubled by `isIdentified` in the api.

Not demanding a change. But all a fixture needs is to have an id, and if it wants, functions like `added` and `removed`.
</blockquote></details>

Will remove the Vue stuff. Can always be added back in if we decide the fixture needs ui stuff.  I think that singular bool in the state isn't actually used at all and was something I had just put there in the beginning.
___
*[`src/fixtures/hilight/api/hilight.ts` line 40 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1yOB105VRQKJJgZuHC:-N2Y2ZYQ8a01DRWVYEsi:bgrxzxd) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/api/hilight.ts#L40)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

not 100% (still trying to assemble how everything hangs together), but you might want to wait on `map.viewPromise`. If there is no view (which maybe could happen if this goes early), then this logic would skip and never revist.  However the risk is you get a stack of `_parseConfig` requests and then they race when the view finally appears.  Maybe put a `TODO` for now to revist? Its the sort of thing to tidy up when all the guts are working.

Also we probably need a listener / watcher of sorts to detect when the esriView gets destroyed and recreated. The code below will need to be re-applied. Sharven has samples of this around his reprojection code. Look at mappy stuff like scrollguard and crosshairs if you cant find it.
</blockquote></details>

Noted in the code, thanks
___
*[`src/fixtures/hilight/api/hilight.ts` line 52 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1yP7jT6U0keHgvdKLY:-N2Y1cud5WSnln_dRayx:b-dnaai3) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/api/hilight.ts#L52)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

redundant?
</blockquote></details>

yup lol. donethanks
___
*[`src/fixtures/hilight/api/hilight.ts` line 67 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N1yPWgs6vTKsnEMVI8K:-N2Y9uWoBFKgC8QEH1tP:b-1nyg3m) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/api/hilight.ts#L67)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

doesn't really matter, but if you want to avoid raw for loops you can do
```
await Promise.all(gs.map(g => hilightLayer.addGraphic(g)));
```

UNLESS they need to go one at a time, in order. in which case there might be a clever trick but I'm not seeing it so keep as is. `addGraphic` is only async due to it reprojecting any geometry into the map's spatial reference. For highlighting it should always be the same; and even if not, I don't see any concurrency collisions other than which duplicate-named graphic would error first.
</blockquote></details>

personally not a raw for loop hater, but using the array methods is very Javascript-like. will change over!
___
*[`src/fixtures/hilight/api/hilight-defs.ts` line 2 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N2DNArH-kfmD2EQvc7d:-N2Y39-b-hUs-lZcHjMO:bah2568) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/api/hilight-defs.ts#L2)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

You could put the layer name (`Ramp-Highlight`) in this file as a const then use it in the other spots.
</blockquote></details>

Donethanks
___
*[`src/fixtures/hilight/api/hilight-mode/base-hilight-mode.ts` line 19 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N2DPRyC1dPWVx6QeAW1:-N2Y34FyCQcjCsYzfiVB:b-q8ilnv) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/api/hilight-mode/base-hilight-mode.ts#L19)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

nah. Let someone build a combo class that manages the merge inside it.  Having multiple random hiliters active could get all kinds of collisions; sharing layer fights, split layers in wrong order, effects in wrong order, etc.
</blockquote></details>

gotcha
___
*[`src/fixtures/hilight/api/hilight-mode/glow-hilight-mode.ts` line 30 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/4#-N2DOa-_6lGgco0SWhOO:-N2Y6LKi2goZ0kRyOhye:bdpofh9) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/ba479e67a83acb8cc58e1697578f59e4a45248b1/src/fixtures/hilight/api/hilight-mode/glow-hilight-mode.ts#L30)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I'm assuming we need the actual ESRI graphic lurking in the layer, yeah? Makes sense I suppose. That's a shame, was hoping we could just fire of `.toESRI()` calls everywhere but that return value comes out of nowhere. The alternative is to have RAMP Graphics start tracking their ESRI counterparts with internal pointer, but then we're hardlinking to layers and RAMP Graphics are supposed to be :sparkles: ethereal :sparkles:
</blockquote></details>

Yeah, from what I know we need to actual ESRI graphic to apply that ESRI highlight
___
*[`src/geo/layer/common-graphic-layer.ts` line 149 at r2](https://reviewable.io/reviews/james-rae/ramp4 [...]

2022-07-06 16:18 UTC, closed without merging