Feature Hilighting
james-rae/ramp4-pcar4 pull request #5
Opened 2022-07-06 16:51 UTC by elsa-huang

🎉 🎉 🎉 
- Hilighter no longer deals with grabbing the graphics for a hilight
- Details passes identified graphics to the hilighter
- No more fancy HilightGraphics
- 3 hilight modes as of now: GLOW, LIFT, NONE
  - NONE is the base hilighter. There's no hilight, nothing happens. Will also be set to this if `hilight` nugget isn't defined in the config.
  - LIFT will populate the graphics and nothing else. Other hilighters (like GLOW and FOG) can inherit. Probably what a maptip highlighter would want.
  - GLOW does the esri highlight.
- Details highlight remover specifics
  - Toggler always starts on (unless we want a config flag for this?) when the details panel is opened
    - This means that closing the details panel and then opening it again by clicking a layer from the identify panel will reset the toggler
  - Toggling off will remove the hilight
  - Scrolling between items and switching between the item/result screens does not reset the toggler
  - As long as details is still open, switching between different layer results does not reset the toggler
  - Closing the details panel always removes the hilight
  - Minimizing the details panel removes the hilight, but remembers the toggle value
  - Panning does not remove the hilight
  - Both details screens use the same Toggler, maybe want to move it into its own Vue file like how the settings panel has it
- I just realized I forgot to update the schema. For now, the config nugget just has `mode` and `options`.
- Also just realized I forgot to double check on what we wanted to do when the details panel is opened from other sources (i.e., the grid). Right now it always does a hilight when the details panel opens.

2022-07-06 18:18 UTC, james-rae commented
Focus ring on highlight toggler is funny. It looks ok on layer settings panel so maybe some details local CSS is fighting it?  ![toggle\_focus.png](https://files.reviewableusercontent.io/images/reviewable/7585245/O_UZDHgC4s1krxIBIJMecaWa/toggle_focus.png)





<!-- Sent from Reviewable.io -->

2022-07-06 19:13 UTC, james-rae requested changes
> Reviewed 13 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5)* status: 13 of 21 files reviewed, 13 unresolved discussions (waiting on @elsa-huang and @james-rae)

___
*[`docs/app/defaults.md` line 129 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JfIOs-qJitw-gvxSe:-N6JfIOs-qJitw-gvxSf:b-1y21gu) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/docs/app/defaults.md#L129)):*
> ```Markdown
> | Event Name                           | Payload                                                 | Event Announces                                                |
> | ------------------------------------ | ------------------------------------------------------- | -------------------------------------------------------------- |
> | DETAILS_CLOSED <br> 'details/closed' | none | The details panel was closed.
> ```

could we just leverage the `PANEL_CLOSED` event and inspect the payload for the `details` panel?
___
*[`docs/app/defaults.md` line 130 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JfOn5CdMJfUYwMMS0:-N6JfOn5CdMJfUYwMMS1:b-njukd3) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/docs/app/defaults.md#L130)):*
> ```Markdown
> | ------------------------------------ | ------------------------------------------------------- | -------------------------------------------------------------- |
> | DETAILS_CLOSED <br> 'details/closed' | none | The details panel was closed.
> | DETAILS_MINIMIZED <br> 'details/minimized' | none | The details panel was minimized.
> ```

if the above question is "yes", could we make a general `PANEL_MINIMIZED` event instead?
___
*[`src/api/event.ts` line 684 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JgDLe3SLPKb_f188F:-N6JgDLe3SLPKb_f188G:b-ly5jbc) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/34dc31285bf1ef587627548eb01529efe98d2c8a/src/api/event.ts#L684)):*
> ```XML
>                 // when map clicks, run the identify action
>                 zeHandler = (clickParam: MapClick) => {
>                     if (clickParam.button === 0) {
> ```

should this have been deleted? I think removing this line makes right-click run identify, which we don't want.
___
*[`src/fixtures/details/item-screen.vue` line 14 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6Jg_5a7_tmGJ0Zmkyd:-N6Jg_5a7_tmGJ0Zmkye:bv547ok) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/item-screen.vue#L14)):*
> ```Vue
>                 <!-- highlight toggle -->
>                 <div class="p-8 mb-8 bg-gray-100 flex justify-between">
>                     <div>Toggle Highlight</div>
> ```

hardcoded, needs language thing
___
*[`src/fixtures/details/item-screen.vue` line 22 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6Jj6fK2Yy10giIKnjl:-N6Jj6fK2Yy10giIKnjm:byh9z1f) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/item-screen.vue#L22)):*
> ```Vue
>                 </div>
>                 <!-- paginator and list button for multiple features -->
>                 <div
> ```

this div has been pushed down. We have the `{{ layerName }}` now sitting above it, so mildly concerned if we have the `no layer` case that the above name binding is going to explode.
___
*[`src/fixtures/details/item-screen.vue` line 263 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JjhPED-ePklYx0D63:-N6JjhPED-ePklYx0D64:b-rtagwg) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/item-screen.vue#L263)):*
> ```Vue
>          */
>         identifyItem(): IdentifyItem {
>             // console.log(this.result.items[this.currentIdx]);
> ```

delete
___
*[`src/fixtures/details/item-screen.vue` line 356 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JjsMjCZDvk4BzcuF8:-N6JjsMjCZDvk4BzcuF9:b-x7uu9z) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/item-screen.vue#L356)):*
> ```Vue
>          */
>         detailsMinimized() {
>             // TODO: on minimize, do we want to keep the hilight?
> ```

probably no??
___
*[`src/fixtures/details/layers-screen.vue` line 96 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JlD6QC90wpvRIqr03:-N6JlD6QC90wpvRIqr04:b-flyxgm) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/layers-screen.vue#L96)):*
> ```Vue
>             this.$iApi.event.on(
>                 GlobalEvents.DETAILS_CLOSED,
>                 () => () => (this.activeGreedy = 0)
> ```

curious about the double function `() => () =>`. A required scope trick, or just cut n paste error?
___
*[`src/fixtures/details/layers-screen.vue` line 102 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6Jlj4A6JGNoELSkob9:-N6Jlj4A6JGNoELSkobA:bbf9hym) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/layers-screen.vue#L102)):*
> ```Vue
>     beforeUnmount() {
>         this.watchers.forEach(unwatch => unwatch());
>         this.handlers.forEach(handler => this.$iApi.event.off(handler));
> ```

do you need to clear out the handlers array after turning them off? Else I can see this array growing every time layers gets mounted.

`off()` is currently silent when it can't find the target, if we did that TODO i imagine this code would start shrieking on the console lol

or does everything get destroyed after unmount?
___
*[`src/fixtures/details/result-screen.vue` line 19 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JmjB78KvKQQBfw7Ns:-N6JmjB78KvKQQBfw7Nt:be9cbmx) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/result-screen.vue#L19)):*
> ```Vue
>                     <!-- highlight toggle -->
>                     <div class="p-8 mb-8 bg-gray-100 flex justify-between">
>                         <div>Toggle Highlight</div>
> ```

another language criminal
___
*[`src/fixtures/details/result-screen.vue` line 109 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JqHvt-d-8tqU_FUYU:-N6JqHvt-d-8tqU_FUYV:boynj9k) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/result-screen.vue#L109)):*
> ```Vue
>             hilightToggle: true,
>             // toggle classes from settings panel toggle
>             toggleClasses: {
> ```

given these are copied from settings, and are now x3 in code, probably want to abstract this somehow to a common definition.
___
*[`src/fixtures/details/api/details.ts` line 158 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JtCJBBTe1o6Zr6RL7:-N6JtCJBBTe1o6Zr6RL8:bt9s7lg) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/api/details.ts#L158)):*
> ```XML
>         layerUid: string
>     ) {
>         // hilight all geometries for this layer
> ```

comment should say `all provided identify items`.
___
*[`src/fixtures/details/api/details.ts` line 166 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JsYL-5IHEsnk9s7pS:-N6JsYL-5IHEsnk9s7pT:b-v80lv6) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/api/details.ts#L166)):*
> ```XML
>             if (hilightFix) {
>                 await hilightFix.removeHilight(
>                     hilightFix.getGraphicsByOrigin('details')
> ```

my inner first year CS student is demanding this string be a `const` at module level.  Or maybe put in `hilight-defs`


<!-- Sent from Reviewable.io -->

2022-07-06 20:44 UTC, elsa-huang reviewed
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5)* status: 13 of 21 files reviewed, 13 unresolved discussions (waiting on @elsa-huang and @james-rae)

___
*[`docs/app/defaults.md` line 129 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JfIOs-qJitw-gvxSe:-N6K9zAJA-97AzQtg8Nk:b-ymoyof) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/docs/app/defaults.md#L129)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

could we just leverage the `PANEL_CLOSED` event and inspect the payload for the `details` panel?
</blockquote></details>

Currently doing a check in the panel `close()` function that then emits the `DETAILS_CLOSED` event, so should be possible to get rid of `DETAILS_CLOSED` and do the check in the details panel instead. `PANEL_MINIMIZED` event can be made 
___
*[`docs/app/defaults.md` line 130 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JfOn5CdMJfUYwMMS0:-N6KEv0p3RsEkr-B1JEA:b4c9lyr) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/docs/app/defaults.md#L130)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

if the above question is "yes", could we make a general `PANEL_MINIMIZED` event instead?
</blockquote></details>

:thumbsup: 
___
*[`src/api/event.ts` line 684 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JgDLe3SLPKb_f188F:-N6K9YKH1PADHZ-WTrgW:b-7olwfl) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/34dc31285bf1ef587627548eb01529efe98d2c8a/src/api/event.ts#L684)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

should this have been deleted? I think removing this line makes right-click run identify, which we don't want.
</blockquote></details>

Oh yup, probably deleted it by accident while removing the hilight stuff from here
___
*[`src/fixtures/details/item-screen.vue` line 14 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6Jg_5a7_tmGJ0Zmkyd:-N6KAgAW5YLXvU9xtO1T:bw8loyo) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/item-screen.vue#L14)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

hardcoded, needs language thing
</blockquote></details>

Oops, right
___
*[`src/fixtures/details/item-screen.vue` line 22 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6Jj6fK2Yy10giIKnjl:-N6KAyBMBPXknSQbe4qJ:b-xk06sm) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/item-screen.vue#L22)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

this div has been pushed down. We have the `{{ layerName }}` now sitting above it, so mildly concerned if we have the `no layer` case that the above name binding is going to explode.
</blockquote></details>

No problem, can add a `v-if` check to the layer name div
___
*[`src/fixtures/details/item-screen.vue` line 263 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JjhPED-ePklYx0D63:-N6KEjddCi9UObFW62Tb:b4c9lyr) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/item-screen.vue#L263)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

delete
</blockquote></details>

:thumbsup: 
___
*[`src/fixtures/details/item-screen.vue` line 356 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JjsMjCZDvk4BzcuF8:-N6KBsbj5Ubsq5ufhzrD:b-ptwt8t) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/item-screen.vue#L356)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

probably no??
</blockquote></details>

yeah, probably not, lol
___
*[`src/fixtures/details/layers-screen.vue` line 96 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JlD6QC90wpvRIqr03:-N6KC-vH7yqfvoLOqTMp:bdhtb8v) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/layers-screen.vue#L96)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

curious about the double function `() => () =>`. A required scope trick, or just cut n paste error?
</blockquote></details>

Probably a copy-paste error ... will double check
___
*[`src/fixtures/details/layers-screen.vue` line 102 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6Jlj4A6JGNoELSkob9:-N6KCNsU7G61Nk3rJwSA:bnj800j) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/layers-screen.vue#L102)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

do you need to clear out the handlers array after turning them off? Else I can see this array growing every time layers gets mounted.

`off()` is currently silent when it can't find the target, if we did that TODO i imagine this code would start shrieking on the console lol

or does everything get destroyed after unmount?
</blockquote></details>

Hm, not sure. Other components seem to just be turning off and not clearing it out and haven't seen any issues. Will check what's happening with the array.
___
*[`src/fixtures/details/result-screen.vue` line 19 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JmjB78KvKQQBfw7Ns:-N6KD0m01J1lMVMAm15s:bi75z5j) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/result-screen.vue#L19)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

another language criminal
</blockquote></details>

:writing_hand: :pensive: 
___
*[`src/fixtures/details/result-screen.vue` line 109 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JqHvt-d-8tqU_FUYU:-N6KDzpKAZpdqZgkfbof:bxs4i17) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/result-screen.vue#L109)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

given these are copied from settings, and are now x3 in code, probably want to abstract this somehow to a common definition.
</blockquote></details>

mhm, maybe to `/components/controls` ?
___
*[`src/fixtures/details/api/details.ts` line 158 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JtCJBBTe1o6Zr6RL7:-N6KEFt-Aqj5yPVaWxIF:b-po3q52) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/api/details.ts#L158)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

comment should say `all provided identify items`.
</blockquote></details>

Noted, thanks
___
*[`src/fixtures/details/api/details.ts` line 166 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JsYL-5IHEsnk9s7pS:-N6KEH5UBFRt-T9xUayB:bebrt1w) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/api/details.ts#L166)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

my inner first year CS student is demanding this string be a `const` at module level.  Or maybe put in `hilight-defs`
</blockquote></details>

Will do


<!-- Sent from Reviewable.io -->

2022-07-07 13:11 UTC, james-rae commented
*[`src/fixtures/details/result-screen.vue` line 109 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JqHvt-d-8tqU_FUYU:-N6NmEB65DGZuQM_eg3k:bai35in) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/result-screen.vue#L109)):*
<details><summary><i>Previously, elsa-huang wrote…</i></summary><blockquote>

mhm, maybe to `/components/controls` ?
</blockquote></details>

I'll run this by our good pal Spencer


<!-- Sent from Reviewable.io -->

2022-07-07 13:28 UTC, james-rae commented
*[`src/fixtures/details/result-screen.vue` line 109 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JqHvt-d-8tqU_FUYU:-N6NqDld-gHjXtVqtWyE:b-i17itb) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/result-screen.vue#L109)):*
Spencer sez

> I would wrap it in a component in `components/controls` . The only thing I don't know is if the `@change` event will get up the extra level without having to emit it on the wrapper again.


<!-- Sent from Reviewable.io -->

2022-07-07 15:58 UTC, james-rae requested changes
General thought to go with your schema comment. We might want to consider "glow" being the default, and have the "off" case be a specific setting. 
What your proposing is if no hilighter specified, we are "off" mode. 
What i'm saying is, 
  if nothing specified, defaults to "glow"
  if "none" specified, then goes to off.

Thinking is average author wants highlighter, so we don't want to make them "config" it every time.  Make them config the off scenario.

> Reviewed 8 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-:-N6ON4Tj6-Dscz1rZ5qK:b-2v83jc)* status: all files reviewed, 28 unresolved discussions (waiting on @elsa-huang and @james-rae)

___
*[`src/fixtures/hilight/api/hilight.ts` line 1 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O04dbAeDWMNzV34UQ:-N6O04dcEzk6pJSFNN0a:b-9123mq) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L1)):*
> ```XML
> import { FixtureInstance, GlobalEvents } from '@/api';
> ```

move these into the `internal` import below. It likely wont make a difference but using internal insulates us from circular import madness

later edit - i searched the codebase and saw we're really inconsistent throughout ramp, so now this one is a shrug
___
*[`src/fixtures/hilight/api/hilight.ts` line 8 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O16Nr6wPM-CDH65VC:-N6O16Nr6wPM-CDH65VD:b-u38h52) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L8)):*
> ```XML
> import { GlowHilightMode } from './hilight-mode/glow-hilight-mode';
> import { HILIGHT_LAYER_NAME } from './hilight-defs';
> import { LiftHilightMode } from './hilight-mode/lift-hilight-mode';
> ```

this import is lonely!! Move it up a line to hang with its highlighty friends.
___
*[`src/fixtures/hilight/api/hilight.ts` line 17 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O1P_m8u5mb4rjvgHX:-N6O1P_m8u5mb4rjvgHY:bxuo8md) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L17)):*
> ```XML
>         // create the hilight layer
>         console.log(this);
>         if (this.$iApi.geo.map.created) {
> ```

bit curious about this entire `if` structure. If the map is already created when this fixture loads, then the `initHilightLayer` will only get called once. But if fixture loads before the map, then `initHilightLayer` gets called every time a map gets created.  

If the intention is to do it only one time, then change `event.on()` to `event.once()`.

If we need to be re-making the layer on a new map, we probably need the `on` to be set outside the `if`, and then do a `created` check to force a trigger because it this code might have missed the first `MAP_CREATED` event.

To be honest I'm not 100% about when map created gets called anymore since our buddy Sharven has refactored that process a number of times. And when a new map is created, are the fixtures also regenerated? Cuz if fixtures are also regen'd then we will hit this constructor again (i think?) so we just need the one-time. Also not sure what triggers full map re-create anymore. Loading a new config? Language change? I believe projection change just kills the view, not the map.
___
*[`src/fixtures/hilight/api/hilight.ts` line 46 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O3Ekx3DZRUqFjMIhA:-N6O3Ekx3DZRUqFjMIhB:b16h2n9) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L46)):*
> ```XML
>                     this.$iApi
>                 );
>         }
> ```

add a `default:` block that puts a console error and has the string it couldn't match in the console message
___
*[`src/fixtures/hilight/api/hilight.ts` line 55 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O40jz3k0AyXEvXx-s:-N6O40jz3k0AyXEvXx-t:b-xh1tdc) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L55)):*
> ```XML
>             cosmetic: true
>         });
>         await hilightLayer.initiate();
> ```

mohsin has a pending fix that will make `addLayer` do the `initiate` for us. Lets add a TODO to remove the initiate after issue 1020 is pulled. 
___
*[`src/fixtures/hilight/api/hilight.ts` line 61 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6OKo6z1dwoSazqbc-8:-N6OKo6z1dwoSazqbc-9:b3dg55h) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L61)):*
> ```XML
>     async addHilight(graphics: Array<Graphic> | Graphic) {
>         const gs = graphics instanceof Array ? graphics : [graphics];
>         await this.hilightMode.addGraphics(gs);
> ```

so `add/remove` and `toggleOn/Off` are bound one-to-one, and there is no API for toggling existing items.  I feel these functions are named to reflect what the hilighter mode is doing, but they're really the same "purpose". I think we can clean up the mode interface signature if we always treat "add" as hilighting something, and "remove" as unhilighting. 
So we can get rid of the toggle functions, and in your Glow highlighter code, it looks something like

```
async addGraphics(graphics: Array<Graphic>) {
   await super.addGraphics(graphics); // blocks on the lift doing it's thang
   // all the code currently in toggle on function now goes here
}
```
___
*[`src/fixtures/hilight/api/hilight.ts` line 75 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6OLyFw726rDP2yyjnY:-N6OLyFw726rDP2yyjnZ:b71c689) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L75)):*
> ```XML
>     }
> 
>     getGraphicsByOrigin(origin: string): Array<Graphic> {
> ```

I like how this works, how its being used by details is grand; gets rid of a lot of concerns I had earlier. 
But a grousing nag I have is that our HighlightAPI has this function about "origin", and internalizes the use, but its the only real spot you see origin, the origin is really managed by the caller.
My proposal, which you can banhammer, is shift this function to be about searching by GraphicKey. So it aligns with the other two methods, and presents the api as "i deal with graphic keys and things used to make graphic keys".  Also provided some more search capability, like find every hilight tied to a `uid`.

Psuedocode
```
getGraphicByKey(origin: string | undefined, uid: string | undefined, oid: number | undefined): Array<Graphic> {
  // existing layer getting code HERE
  
  // this makes array of deconstructed keys, but tacks the graphic on as a 4th value
  let keys = hilightLayer.graphics.map(g => ({
    ...this.deconstructGraphicKey(g.id),
    og = g
   });
  
  if (origin) {  
    keys = keys.filter(k => k.origin === origin)
  }

  if (uid) {  
    keys = keys.filter(k => k.uid === uid)
  }  
  
  if (oid) {  
    keys = keys.filter(k => k.oid === oid)
  }
  
  return keys.map(k => keys.og);
}
```
___
*[`src/fixtures/hilight/api/hilight.ts` line 96 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O9P2A70IIpYQd8A7a:-N6O9P2B0bRqyGPI9Ymx:b-nnhglh) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L96)):*
> ```XML
>         origin: string;
>         uid: string;
>         oid: string;
> ```

too lazy to go back at how the code consumes this, but since `oid` is a number coming in on the creation function, should we cast back to `number` here?
___
*[`src/fixtures/hilight/api/hilight.ts` line 99 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O7Pj9ERvN7kSS6_EX:-N6O7Pj9ERvN7kSS6_EY:b-agzozj) ([raw file](https://github.com/james-rae [...]

2022-07-07 16:43 UTC, james-rae commented
*[`src/fixtures/hilight/api/hilight.ts` line 61 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6OKo6z1dwoSazqbc-8:-N6OXm134igJMNf8xnUL:b-rjtsea) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L61)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

so `add/remove` and `toggleOn/Off` are bound one-to-one, and there is no API for toggling existing items.  I feel these functions are named to reflect what the hilighter mode is doing, but they're really the same "purpose". I think we can clean up the mode interface signature if we always treat "add" as hilighting something, and "remove" as unhilighting. 
So we can get rid of the toggle functions, and in your Glow highlighter code, it looks something like

```
async addGraphics(graphics: Array<Graphic>) {
   await super.addGraphics(graphics); // blocks on the lift doing it's thang
   // all the code currently in toggle on function now goes here
}
```
</blockquote></details>

you could even change the functions to just be `.add()` and `.remove()`, since the param makes it clear it takes graphics


<!-- Sent from Reviewable.io -->

2022-07-07 16:47 UTC, james-rae commented
*[`src/fixtures/details/item-screen.vue` line 13 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6OYe428lUClJZh_6ga:-N6OYe428lUClJZh_6gb:banfljv) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/item-screen.vue#L13)):*
> ```Vue
>                 </div>
>                 <!-- highlight toggle -->
>                 <div class="p-8 mb-8 bg-gray-100 flex justify-between">
> ```

we might need some kind of `v-if` in case the hilighter mode is the off mode. otherwise i think this toggle appears and does nothing


<!-- Sent from Reviewable.io -->

2022-07-20 21:14 UTC, elsa-huang reviewed
Focus ring fixed itself when it was abstracted to `/components` :shrug: 

`GLOW` being default makes sense. Donethanks.

Hopefully I got everything :crossed_fingers: 

> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-:-N7SKvxz3bb4_7lVbl7A:b-msggn3)* status: all files reviewed, 29 unresolved discussions (waiting on @james-rae)

___
*[`src/fixtures/details/item-screen.vue` line 13 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6OYe428lUClJZh_6ga:-N7SKdzY8KqZeJprmRrw:b-mhsq5s) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/item-screen.vue#L13)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

we might need some kind of `v-if` in case the hilighter mode is the off mode. otherwise i think this toggle appears and does nothing
</blockquote></details>

donethanks
___
*[`src/fixtures/details/result-screen.vue` line 109 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JqHvt-d-8tqU_FUYU:-N7NDJ8uCuF15V4MGWzu:bah2568) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/result-screen.vue#L109)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

Spencer sez

> I would wrap it in a component in `components/controls` . The only thing I don't know is if the `@change` event will get up the extra level without having to emit it on the wrapper again.
</blockquote></details>

Donethanks
___
*[`src/fixtures/details/api/details.ts` line 166 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JsYL-5IHEsnk9s7pS:-N7NDkqe8SjnHIJhyPpk:b-r11wrl) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/api/details.ts#L166)):*
<details><summary><i>Previously, elsa-huang wrote…</i></summary><blockquote>

Will do
</blockquote></details>

reviewable didn't mark this one as done :monkey: 
___
*[`src/fixtures/hilight/api/hilight.ts` line 1 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O04dbAeDWMNzV34UQ:-N7NFuEK6slaRV0uq1RK:bb4jsc7) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L1)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

move these into the `internal` import below. It likely wont make a difference but using internal insulates us from circular import madness

later edit - i searched the codebase and saw we're really inconsistent throughout ramp, so now this one is a shrug
</blockquote></details>

done it anyway :thumbsup: 
___
*[`src/fixtures/hilight/api/hilight.ts` line 8 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O16Nr6wPM-CDH65VC:-N7NFsXn3C7k9dNumx4s:b4c9lyr) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L8)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

this import is lonely!! Move it up a line to hang with its highlighty friends.
</blockquote></details>

:thumbsup: 
___
*[`src/fixtures/hilight/api/hilight.ts` line 17 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O1P_m8u5mb4rjvgHX:-N7NG08q7tYZBC5dlcp1:b-ri08s7) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L17)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

bit curious about this entire `if` structure. If the map is already created when this fixture loads, then the `initHilightLayer` will only get called once. But if fixture loads before the map, then `initHilightLayer` gets called every time a map gets created.  

If the intention is to do it only one time, then change `event.on()` to `event.once()`.

If we need to be re-making the layer on a new map, we probably need the `on` to be set outside the `if`, and then do a `created` check to force a trigger because it this code might have missed the first `MAP_CREATED` event.

To be honest I'm not 100% about when map created gets called anymore since our buddy Sharven has refactored that process a number of times. And when a new map is created, are the fixtures also regenerated? Cuz if fixtures are also regen'd then we will hit this constructor again (i think?) so we just need the one-time. Also not sure what triggers full map re-create anymore. Loading a new config? Language change? I believe projection change just kills the view, not the map.
</blockquote></details>

I think this is supposed to be `.once()`. I think you mentioned it before in the old PR but I must have forgotten and changed it back to `.on()` at some point.
___
*[`src/fixtures/hilight/api/hilight.ts` line 46 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O3Ekx3DZRUqFjMIhA:-N6iTPmJ2xgmjN1J_bsX:b6uqlmc) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L46)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

add a `default:` block that puts a console error and has the string it couldn't match in the console message
</blockquote></details>

In this case do we want to set to `NONE` mode, or still have `GLOW` on?
___
*[`src/fixtures/hilight/api/hilight.ts` line 55 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O40jz3k0AyXEvXx-s:-N7SJ7EtDQc70ZyMnZ2c:b-8ah7ln) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L55)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

mohsin has a pending fix that will make `addLayer` do the `initiate` for us. Lets add a TODO to remove the initiate after issue 1020 is pulled. 
</blockquote></details>

It's pulled now I believe, so will be removing
___
*[`src/fixtures/hilight/api/hilight.ts` line 61 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6OKo6z1dwoSazqbc-8:-N7SJG-p9n04wxqg_XI1:b-zfs5sg) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L61)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

you could even change the functions to just be `.add()` and `.remove()`, since the param makes it clear it takes graphics
</blockquote></details>

That makes sense, I'm too used to seeing the add and toggle as 2 completely separate things, I guess.
___
*[`src/fixtures/hilight/api/hilight.ts` line 75 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6OLyFw726rDP2yyjnY:-N7SJStY7MtWDl2g4lVE:b-u3rdsj) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L75)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

I like how this works, how its being used by details is grand; gets rid of a lot of concerns I had earlier. 
But a grousing nag I have is that our HighlightAPI has this function about "origin", and internalizes the use, but its the only real spot you see origin, the origin is really managed by the caller.
My proposal, which you can banhammer, is shift this function to be about searching by GraphicKey. So it aligns with the other two methods, and presents the api as "i deal with graphic keys and things used to make graphic keys".  Also provided some more search capability, like find every hilight tied to a `uid`.

Psuedocode
```
getGraphicByKey(origin: string | undefined, uid: string | undefined, oid: number | undefined): Array<Graphic> {
  // existing layer getting code HERE
  
  // this makes array of deconstructed keys, but tacks the graphic on as [...]

2022-07-20 21:18 UTC, elsa-huang commented
PR to main soon? 👀

2022-07-20 21:18 UTC, elsa-huang reviewed
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5)* status: 4 of 25 files reviewed, 29 unresolved discussions (waiting on @james-rae)

___
*[`src/fixtures/hilight/api/hilight-mode/glow-hilight-mode.ts` line 22 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6OE0D07_gCFz04cB-Q:-N7STBMm-4pm2wgxvAja:bdjg8lv) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight-mode/glow-hilight-mode.ts#L22)):*
<details><summary><i>Previously, elsa-huang wrote…</i></summary><blockquote>

:thumbsup: I'm thinking that it'll be enough for anything that inherits to call `super()` in the constructor
</blockquote></details>

Oh, I said that but I still made it protected LOL ... will change it in a later push


<!-- Sent from Reviewable.io -->

2022-07-21 18:04 UTC, james-rae requested changes
> Reviewed 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5)* status: all files reviewed, 3 unresolved discussions (waiting on @elsa-huang)

___
*[`schema.json` line 2065 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N7Wqx3t3r3yd70M7gmf:-N7Wqx3t3r3yd70M7gmg:b-62zfxr) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/35e83e8fda4a41691702a76cf4f14771dae9f29d/schema.json#L2065)):*
> ```JSON
>                         },
>                         "options": {
>                             "description": "Options for the selected hilight mode.",
> ```

Agree with generic object. We can flush out some fancy doc page later
___
*[`src/api/event.ts` line 684 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6JgDLe3SLPKb_f188F:-N7WrH1B9nrr_y_Pz3iH:b-frolu7) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/34dc31285bf1ef587627548eb01529efe98d2c8a/src/api/event.ts#L684)):*
<details><summary><i>Previously, elsa-huang wrote…</i></summary><blockquote>

Oh yup, probably deleted it by accident while removing the hilight stuff from here
</blockquote></details>

original thing fixed, but now we lost an `=`. `===` for maximum respect
___
*[`src/fixtures/details/item-screen.vue` line 358 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N7WryVK1mnbf3urukWu:-N7WryVK1mnbf3urukWv:b-7e7ybt) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/35e83e8fda4a41691702a76cf4f14771dae9f29d/src/fixtures/details/item-screen.vue#L358)):*
> ```Vue
>         detailsMinimized() {
>             this.details.removeDetailsHilight();
>             // TODO: do we want to keep track of the index on minimize?
> ```

Lets keep this TODO lurking; I feel we need to play with it in full build to get proper desired behaviors nailed down.
___
*[`src/fixtures/details/layers-screen.vue` line 102 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6Jlj4A6JGNoELSkob9:-N7WsLIF9tQm_ZNEZnhV:b-joi024) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/details/layers-screen.vue#L102)):*
<details><summary><i>Previously, elsa-huang wrote…</i></summary><blockquote>

Hm, not sure. Other components seem to just be turning off and not clearing it out and haven't seen any issues. Will check what's happening with the array.
</blockquote></details>

probably all good due to unmount. will close this grouse
___
*[`src/fixtures/details/api/details.ts` line 12 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N7WsogT1Oyo6GGqVDc8:-N7WsogT1Oyo6GGqVDc9:bad42fo) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/35e83e8fda4a41691702a76cf4f14771dae9f29d/src/fixtures/details/api/details.ts#L12)):*
> ```XML
> 
> import type { HilightAPI } from '../../hilight/api/hilight';
> import { HilightMode } from '@/fixtures/hilight/api/hilight-defs';
> ```

lol lets pick one path convention for the imports.  Or you can use one line and sneak the `type` inside the brackets.
___
*[`src/fixtures/hilight/api/hilight.ts` line 46 at r1](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N6O3Ekx3DZRUqFjMIhA:-N7WuNaM4WXwCO_cz3yW:bee4wvr) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/e964ed04b1973ca5db6338bb90756a7ef8275e1f/src/fixtures/hilight/api/hilight.ts#L46)):*
<details><summary><i>Previously, elsa-huang wrote…</i></summary><blockquote>

In this case do we want to set to `NONE` mode, or still have `GLOW` on?
</blockquote></details>

Sure NONE feels the safest. Only people with smart config files deserve highlighting.


<!-- Sent from Reviewable.io -->

2022-07-21 18:09 UTC, james-rae commented
*[`src/fixtures/details/api/details.ts` line 12 at r2](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5#-N7WsogT1Oyo6GGqVDc8:-N7Wwppr7v5cHatBsKuQ:b-nzrk8a) ([raw file](https://github.com/james-rae/ramp4-pcar4/blob/35e83e8fda4a41691702a76cf4f14771dae9f29d/src/fixtures/details/api/details.ts#L12)):*
<details><summary><i>Previously, james-rae (James Rae) wrote…</i></summary><blockquote>

lol lets pick one path convention for the imports.  Or you can use one line and sneak the `type` inside the brackets.
</blockquote></details>

sneak approach is actually a lie, my bad.


<!-- Sent from Reviewable.io -->

2022-07-25 19:49 UTC, james-rae reviewed
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5)* status: all files reviewed, 1 unresolved discussion (waiting on @elsa-huang)



<!-- Sent from Reviewable.io -->

2022-07-26 15:55 UTC, james-rae reviewed
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/james-rae/ramp4-pcar4/5)* status: all files reviewed, 1 unresolved discussion (waiting on @elsa-huang)



<!-- Sent from Reviewable.io -->

2022-07-27 20:34 UTC, james-rae commented
Closing so I stop getting pings every push lol

2022-07-27 20:34 UTC, closed without merging